---
- name: Base set up
  hosts: client1.otus.lan, client2.otus.lan
  #Выполнять действия от root-пользователя
  become: yes
  tasks:
  #Установка текстового редактора Vim и chrony
  - name: install softs on CentOS
    yum:
      name:
        - vim
        - chrony
      state: present
      update_cache: true
  
  #Отключение firewalld и удаление его из автозагрузки
  - name: disable firewalld
    service:
      name: firewalld
      state: stopped
      enabled: false
  
  #Отключение SElinux из автозагрузки
  #Будет применено после перезагрузки
  - name: disable SElinux
    selinux:
      state: disabled
  
  #Отключение SElinux до перезагрузки
  - name: disable SElinux now
    shell: setenforce 0

  #Установка временной зоны Европа/Москва    
  - name: Set up timezone
    timezone:
      name: "Europe/Moscow"
  
  #Запуск службы Chrony, добавление её в автозагрузку
  - name: enable chrony
    service:
      name: chronyd
      state: restarted
      enabled: true
  
  #Копирование файла /etc/hosts c правами root:root 0644
  - name: change /etc/hosts
    template:
      src: hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: 0644
  
  #Установка клиента Freeipa
  - name: install module ipa-client
    yum:
      name:
        - freeipa-client
      state: present
      update_cache: true
  
  #Запуск скрипта добавления хоста к серверу
  - name: add host to ipa-server
    shell: echo -e "yes\nyes" | ipa-client-install --mkhomedir --domain=OTUS.LAN --server=ipa.otus.lan --no-ntp -p admin -w 12345678


- name: Base set upp
  hosts: ipa.otus.lan
  become: yes
  tasks:
  
  - name: Set up timezone
    timezone:
     name: "Europe/Moscow"
 
  - name: ipv6
    ansible.posix.sysctl:
      name: net.ipv6.conf.lo.disable_ipv6
      value: '0'
      sysctl_set: true
      state: present
 
  - name: Install softs
    yum:
     name:
       - vim
       - chrony
       - '@idm:DL1'
       - ipa-server
       - ipa-server-dns
     state: present
     update_cache: true
    become: true

  - name: enable chrony
    service:
      name: chronyd
      state: restarted
      enabled: true 

  - name: Add hostname
    lineinfile:
      dest: /etc/hosts
      line: '192.168.57.10 ipa.otus.lan ipa'

  - name: Disable firewalld
    service:
      name: firewalld
      state: stopped
      enabled: false

  - name: Disable SElinux
    selinux:
      state: disabled
  
  #Отключение SElinux до перезагрузки
  - name: disable SElinux now
    shell: setenforce 0

  - name: install ipa server
    shell:
      cmd: 'ipa-server-install -p 12345678 -a 12345678 --domain="otus.lan" --realm="OTUS.LAN" --hostname="ipa.otus.lan" --setup-dns --no-forwarders --no-reverse --mkhomedir --unattended'

